name: flutter_sdk_example
description: Flutter demo application to see Phrase OTA in action
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  phrase: ^1.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
